### ISSUE TITLE
twitter api changed

### ISSUE THREAD

**Issue by AlessandroSpallina** [propublica/politwoops-tweet-collector#17]
Running
```
PYTHONPATH=$PYTHONPATH:`pwd`/lib ./bin/tweets-client.py
```

returns 
```
[2021-01-07 17:43:43.028120] ERROR: tweets-client.py: Failed to send request: Failed to parse: https://api.twitter.com/1.1/account/verify_credentials.json
Traceback (most recent call last):
  File "/home/skela/.local/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 2, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://stream.twitter.com/1.1/statuses/filter.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/tweets-client.py", line 232, in <module>
    sys.exit(main(args))
  File "./bin/tweets-client.py", line 213, in main
    return app.run()
  File "./bin/tweets-client.py", line 194, in run
    self.stream_forever()
  File "./bin/tweets-client.py", line 183, in stream_forever
    stream.filter(follow=track_items)
  File "/home/skela/.local/lib/python3.8/site-packages/tweepy/streaming.py", line 474, in filter
    self._start(is_async)
  File "/home/skela/.local/lib/python3.8/site-packages/tweepy/streaming.py", line 389, in _start
    self._run()
  File "/home/skela/.local/lib/python3.8/site-packages/tweepy/streaming.py", line 320, in _run
    six.reraise(*exc_info)
  File "/home/skela/.local/lib/python3.8/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/skela/.local/lib/python3.8/site-packages/tweepy/streaming.py", line 266, in _run
    resp = self.session.request('POST',
  File "/home/skela/.local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/skela/.local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/skela/.local/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/skela/.local/lib/python3.8/site-packages/requests/models.py", line 384, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://stream.twitter.com/1.1/statuses/filter.json
```

this should be caused by the fact that the twitter api changed (https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/migrate/standard-to-twitter-api-v2)

**Comment by bre7** [comment]
Since the v1 API is still supported for streaming, update tweepy (`tweepy==4.5.0`) and use the new Auth API:
https://github.com/propublica/politwoops-tweet-collector/blob/4f063e3bc5a6b784606a179077e16d065e7c5108/bin/tweets-client.py#L134-L135
```diff
- self.twitter_auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
- self.twitter_auth.set_access_token(access_token, access_token_secret)
+ self.twitter_auth = tweepy.OAuth1UserHandler(consumer_key, consumer_secret, access_token, access_token_secret)
```

**Comment by ozanguven** [comment]
Updating to `tweepy==4.5.0` generates additional errors:
```
Traceback (most recent call last):
  File "./bin/tweets-client.py", line 62, in <module>
    class TweetListener(tweepy.streaming.StreamListener):
AttributeError: module 'tweepy.streaming' has no attribute 'StreamListener'
```

**Comment by dwillis** [comment]
@ozanguven yeah, it looks like Tweepy made some significant changes to its API starting with 4.5.0: https://docs.tweepy.org/en/v4.5.0/streaming.html
