### ISSUE TITLE
http error when running tweets-client.py

### ISSUE THREAD

**Issue by mstrstvns** [propublica/politwoops-tweet-collector#9]
When running command ./bin/tweets-client.py the following error is returned.

send: 'GET /1/account/verify_credentials.json HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: api.twitter.com\r\nAuthorization: OAuth realm="", oauth_nonce="85857454", oauth_timestamp="1411050412", oauth_consumer_key="heLP4n2JMqICTTT7fWChOosK6", oauth_signature_method="HMAC-SHA1", oauth_version="1.0", oauth_token="2814994075-XEieBJFHmFwfZxKMHuJ14ODCC9QXcMIh7ibTSyg", oauth_signature="7VQa5SGFUnaGWD5j5mFc0B1gcGI%3D"\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: content-length: 52
header: content-type: application/json;charset=utf-8
header: date: Thu, 18 Sep 2014 14:26:53 UTC
header: server: tsa_a
header: set-cookie: guest_id=v1%3A141105041308460869; Domain=.twitter.com; Path=/; Expires=Sat, 17-Sep-2016 14:26:53 UTC
header: x-connection-hash: ac7127a6a042322fc951f53834b990cb
[2014-09-18 14:26] ERROR: tweets-client.py: [{u'message': u'SSL is required', u'code': 92}]
Traceback (most recent call last):
  File "./bin/tweets-client.py", line 201, in <module>
    sys.exit(main(args))
  File "./bin/tweets-client.py", line 182, in main
    return app.run()
  File "./bin/tweets-client.py", line 159, in run
    self.init_beanstalk()
  File "./bin/tweets-client.py", line 133, in init_beanstalk
    use=tweets_tube)
  File "/home1/geektrek/git/politwoops-tweet-collector/lib/politwoops/utils.py", line 41, in beanstalk
    beanstalk = beanstalkc.Connection(host=host, port=port)
  File "/home1/geektrek/python272/lib/python2.7/site-packages/beanstalkc.py", line 57, in **init**
    self.connect()
  File "/home1/geektrek/python272/lib/python2.7/site-packages/beanstalkc.py", line 61, in connect
    SocketError.wrap(self._socket.connect, (self.host, self.port))
  File "/home1/geektrek/python272/lib/python2.7/site-packages/beanstalkc.py", line 43, in wrap
    raise SocketError(e)
beanstalkc.SocketError: [Errno 111] Connection refused

**Comment by khangaikh** [comment]
Hello there i am trying to work on politwoops and i still getting[2015-04-05 11:51] ERROR: tweets-client.py: [{u'message': u'SSL is required', u'code': 92}] even after tweepy==2,3
please guide me

**Comment by freejoe76** [comment]
@mstrstvns hi, did you figure out that beanstalkc error?

@khangaikh the best way to address this tweepy isssue is to run `pip uninstall tweepy; pip install tweepy`
